[tool.poetry]
name = "minitools"
version = "0.1.0"
description = ""
authors = ["Manolo Santos <manolo.santos@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.test.dependencies]
pytest = "^6.2"
openai = "^1.58.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
